import React from "react";

function Australia(){
    return(
        <div>
            <h3>Australia</h3>
                  <table>
                    <tbody>
                      <tr>
                        <th>From</th>
                        <th>To</th> 
                        <th>Duration</th>
                        <th>F</th>
                        <th>C</th> 
                        <th>Y</th>
                      </tr>
                       <tr>
                         <td>Sydney</td>
                         <td>SFO</td>
                         <td>13h35m</td>
                         <td></td>
                         <td>$310</td>
                         <td>$158</td>
                    </tr>
                       <tr>
                         <td></td>
                         <td>LAX</td>
                         <td>13h50m</td>
                         <td></td>
                         <td>$310</td>
                         <td>$158</td>
                    </tr>
                       <tr>
                         <td></td>
                         <td>IAH</td>
                         <td>15h40m</td>
                         <td></td>
                         <td>$310</td>
                         <td>$158</td>
                    </tr>
                    <tr>
                       <td>---</td>
                    </tr>
                    <tr>
                      <td>Melbourne</td>
                      <td>LAX</td>
                      <td>14h15m</td>
                      <td></td>
                      <td>$284</td>
                      <td>$152</td>
                 </tr>
                    <tr>
                       <td>---</td>
                    </tr>
                    <tr>
                      <td>Auckland</td>
                      <td>SFO</td>
                      <td>12h20m</td>
                      <td></td>
                      <td>$241</td>
                      <td>$109</td>
                 </tr>
                </tbody>
            </table>
        </div>
    )
}
export default Australia;