import React from "react";

function Europe(){
    return(
        <div>
            <h3>Europe</h3>
                <table>
                      <tr>
                            <th>From</th>
                            <th>Destination</th> 
                            <th>Duration</th>
                            <th>First Class</th>
                            <th>Business</th> 
                            <th>Coach</th>
                      </tr>
                     <tr>
                         <td>London</td>
                         <td>EWR</td>
                         <td>8h30m</td>
                         <td></td>
                         <td>$315</td>
                         <td>$250</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>IAD</td>
                        <td>8h45m</td>
                        <td></td>
                        <td>$315</td>
                        <td>$250</td>
                   </tr>
                    <tr>
                        <td></td>
                        <td>ORD</td>
                        <td>9h10m</td>
                        <td>$342</td>
                        <td>$315</td>
                        <td>$250</td>
                   </tr>
                   <tr>
                       <td></td>
                       <td>IAH</td>
                       <td>10h40m</td>
                       <td></td>
                       <td>$317</td>
                       <td>$250</td>
                  </tr>
                  <tr>
                      <td></td>
                      <td>SFO</td>
                      <td>11h05m</td>
                      <td>$397</td>
                      <td>$357</td>
                      <td>$250</td>
                 </tr>
                 <tr>
                       <td></td>
                       <td>LAX</td>
                       <td>11h15m</td>
                       <td> </td>
                       <td>$357</td>
                       <td>$250</td>
                 </tr>
                 <hr/>
                 <tr>
                     <td>Dublin</td>
                     <td>EWR</td>
                     <td>7h30m</td>
                     <td></td>
                     <td>$158</td>
                     <td>$98</td>
                </tr>
                <hr/>
                <tr>
                    <td>Lisbon</td>
                    <td>EWR</td>
                    <td>8h35m</td>
                    <td></td>
                    <td>$184</td>
                    <td>$119</td>
               </tr>
               <hr/>
               <tr>
                   <td>Madrid</td>
                   <td>EWR</td>
                   <td>9h0m</td>
                   <td></td>
                   <td>$182</td>
                   <td>$117</td>
              </tr>
              <hr/>
              <tr>
                  <td>Barcelona</td>
                  <td>EWR</td>
                  <td>9h10m</td>
                  <td></td>
                  <td>$177</td>
                  <td>$112</td>
             </tr>                   
              <hr/>
              <tr>
                  <td>Paris</td>
                  <td>IAD</td>
                  <td>8h45m</td>
                  <td></td>
                  <td>$265</td>
                  <td>$150</td>
             </tr>                   
              <tr>
                  <td></td>
                  <td>EWR</td>
                  <td>9h0m</td>
                  <td></td>
                  <td>$265</td>
                  <td>$150</td>
             </tr>                   
              <tr>
                  <td></td>
                  <td>ORD</td>
                  <td>9h30m</td>
                  <td>$297</td>
                  <td>$267</td>
                  <td>$150</td>
             </tr>                   
              <tr>
                  <td></td>
                  <td>SFO</td>
                  <td>11h20m</td>
                  <td></td>
                  <td>$307</td>
                  <td>$150</td>
             </tr> 
             <hr/>                 
              <tr>
                  <td>Brussels</td>
                  <td>IAD</td>
                  <td>8h45m</td>
                  <td>$211</td>
                  <td>$184</td>
                  <td>$119</td>
             </tr>                   
              <tr>
                  <td></td>
                  <td>EWR</td>
                  <td>9h0m</td>
                  <td></td>
                  <td>$184</td>
                  <td>$119</td>
             </tr>                   
              <tr>
                  <td></td>
                  <td>ORD</td>
                  <td>9h25m</td>
                  <td>$216</td>
                  <td>$186</td>
                  <td>$119</td>
             </tr> 
             <hr/>                  
              <tr>
                  <td>Amsterdam</td>
                  <td>EWR</td>
                  <td>8h40m</td>
                  <td></td>
                  <td>$177</td>
                  <td>$112</td>
             </tr>                   
              <tr>
                  <td></td>
                  <td>IAD</td>
                  <td>9h0m</td>
                  <td></td>
                  <td>$177</td>
                  <td>$112</td>
             </tr>                   
              <tr>
                  <td></td>
                  <td>ORD</td>
                  <td>9h20m</td>
                  <td>$209</td>
                  <td>$179</td>
                  <td>$112</td>
             </tr>                   
              <tr>
                  <td></td>
                  <td>IAH</td>
                  <td>10h20m</td>
                  <td></td>
                  <td>$219</td>
                  <td>$112</td>
                 </tr> 
                 <hr/>                 
                  <tr>
                      <td>Frankfurt</td>
                      <td>IAD</td>
                      <td>9h15m</td>
                      <td>$280</td>
                      <td>$253</td>
                      <td>$188</td>
                 </tr>
                 <tr>
                     <td></td>
                     <td>EWR</td>
                     <td>9h30m</td>
                     <td></td>
                     <td>$253</td>
                     <td>$188</td>
                 </tr>                   
                 <tr>
                     <td></td>
                     <td>ORD</td>
                     <td>9h35m</td>
                     <td>$285</td>
                     <td>$255</td>
                     <td>$188</td>
                 </tr>                   
                 <tr>
                     <td></td>
                     <td>IAH</td>
                     <td>11h20m</td>
                     <td></td>
                     <td>$295</td>
                     <td>$188</td>
                 </tr>                   
                 <tr>
                     <td></td>
                     <td>SFO</td>
                     <td>11h40m</td>
                     <td></td>
                     <td>$295</td>
                     <td>$188</td>
                 </tr>
                 <hr/>                  
                 <tr>
                     <td>Munich</td>
                     <td>IAD</td>
                     <td>9h25m</td>
                     <td>$270</td>
                     <td>$240</td>
                     <td>$173</td>
                 </tr>                   
                 <tr>
                     <td></td>
                     <td>EWR</td>
                     <td>9h30m</td>
                     <td></td>
                     <td>$238</td>
                     <td>$173</td>
                 </tr>                   
                 <tr>
                     <td></td>
                     <td>ORD</td>
                     <td>9h50m</td>
                     <td>$270</td>
                     <td>$240</td>
                     <td>$173</td>
                 </tr>                   
            </table>
        </div>
    )
}

export default Europe;